version: '2'
.catalog:
  name: "Plek"
  version: "v1.0.0"
  description: "Plek 1.0"
  minimum_rancher_version: v1.0.1 
  questions:
    - variable: "token"
      label: "Token"
      description: "Token to access git"
      required: true
      type: "string"
