version: '2'
.catalog:
  name: "Plek"
  version: "v1.0.1"
  description: "Plek 1.0"
  minimum_rancher_version: v1.0.1 
  questions:
    - variable: host_label
      label: "Host Label to Plek App"
      description: |
        Host label to use as Plek 'value' tag.
        Example: 'environment=app'
      required: false
      type: "string"
    - variable: "elasticsearch_source"
      description: "Link to elasticsearch service or stack/service"
      label: "Elasticsearch source"
      type: "service"
      required: true
      default: "es/elasticsearch-clients"
    - variable: "mongo_source"
      description: "Link to mongodb service or stack/service"
      label: "mongodb source"
      type: "service"
      required: true
      default: "mongo/mongodb"
    - variable: "redis_source"
      description: "Link to redis service or stack/service"
      label: "redis source"
      type: "service"
      required: true
      default: "redis/redis-server"
